@FlightBoard_HostAddress = https://localhost:7233

### Get all flights
GET {{FlightBoard_HostAddress}}/api/flights

### Add a new flight
POST {{FlightBoard_HostAddress}}/api/flights
Content-Type: application/json

{
    "FlightNumber": 1234,
    "Destination": "Berlin",
    "DepartureTime": "2026-04-18T22:00:00",
    "Gate": "D7"
}

### Delete a flight by ID
DELETE {{FlightBoard_HostAddress}}/api/flights/1
