@FlightBoard_HostAddress = http://localhost:5085

GET {{FlightBoard_HostAddress}}/api/flights
Accept: application/json

###









### Get all flights
GET {{FlightBoard_HostAddress}}/api/flights

### Add a new flight
POST {{FlightBoard_HostAddress}}/api/flights
Content-Type: application/json

{
    "FlightNumber": 1234,
    "Destination": "Berlin",
    "DepartureTime": "2026-04-18T22:00:00",
    "Gate": "D7",
    "IsDeleted": false
}

### Delete a flight by ID
DELETE {{FlightBoard_HostAddress}}/api/flights/delete/1
